%Data_Load
%Loads data from file generated by open_loop_PID_tuner.vi into MATLAB
%arrays and calculates 

%clear variables
clear time
clear currentSet
clear temperature
clear voltage
clear current

%Import text file and calculate number of entries.
filename = uigetfile('.txt');
rawdata = load(filename);
ArraySize = size(rawdata);
ArrayLength = ArraySize(1);

%Create arrays.
for i = 1:ArrayLength
    time(i) = rawdata(i,1);
    currentSet(i) = rawdata(i,2);
    current(i) = rawdata(i,3);
    voltage(i) = rawdata(i,4);
    temperature(i) = rawdata(i,5);
end

%Calculate resistance and power.
resistance = voltage./current;
power = voltage.*current;

%Open curve fitting tool.
cftool