%TPD Data Load
%Christopher Heidelberger
%Reads .txt files generated by TPD_Controller.vi and creates 1-D arrays
%containing data.

%clear variables
clear date time tempSet currentSet temp pyroTemp current voltage...
    resistance power;

%Import text file.
filename = uigetfile('.txt');
[date, time, tempSet, currentSet, temp, pyroTemp, current, voltage, ...
    resistance] = textread(filename,'%s %f %f %f %f %f %f %f %f',-1,...
    'headerlines',31, 'delimiter', '\t');

%Calculate power.
power = voltage.*current;

%plot data
plot(time, temp, 'r-', time, pyroTemp, 'b-', time, tempSet, 'g-');
title('Temperature v. Time');
xlabel('Time [s]');
ylabel('Temperature [C]');
legend('Measured Temperature (Thermocouple)', ...
    'Measured Temperature(Pyrometer)', 'Temperature Setpoint', 'location',...
    'southeast');
whitebg('white');